Remove metrics-jmx dependency
We were seeing the following:

```
java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter
	at com.datastax.driver.core.Metrics.<init>(Metrics.java:146)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1501)
	at com.datastax.driver.core.Cluster.init(Cluster.java:208)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:376)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:355)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:305)
	at smartthings.cassandra.CassandraConnection.connect(CassandraConnection.java:89)
	at smartthings.migration.MigrationRunner.run(MigrationRunner.java:53)
```
After upgrading to Metrix 4.x

Per:
https://docs.datastax.com/en/developer/java-driver/3.5/manual/metrics/#metrics-4-compatibility

This is adding a call to `.withoutJMXReporting()` to remove the
dependency on `com.codahale.metrics.JmxReporter`